/* eslint-disable @next/next/no-document-import-in-page */
import React, { ReactNode } from "react";
import Header from "./header";
import Sidebar from "./sidebar";
import styles from "@/styles/Home.module.css";
import { ThemeContext } from "@/components/theme/ThemeProvider";
import { useContext } from "react";
import lightStyles from "@/styles//Light.module.css";
import darkStyles from "@/styles//Dark.module.css";
import Head from "next/head";

interface LayoutProps {
  children: ReactNode;
}

const Layout = ({ children }: LayoutProps) => {
  const { theme } = useContext(ThemeContext);
  const containerStyles =
    theme === "dark" ? darkStyles.container : lightStyles.container;
  return (
    <>
    <Head>
        <title>Show Town IT | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Sidebar />
      <main
        className={`${containerStyles} ${styles.container_fullpage} d-flex flex-column justify-content-center align-items-center position-relative`}
        style={{ zIndex: "9" }}
      >
        {children}
      </main>
    </>
  );
};

export default Layout;
