import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import ThemeToggle from '@/components/ThemeToggle'
import { ThemeContext } from '@/components/theme/ThemeProvider'
import { useContext } from 'react'
import lightStyles from '@/styles//Light.module.css';
import darkStyles from '@/styles//Dark.module.css';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  const { theme } = useContext(ThemeContext);
  const containerStyles = theme === 'dark' ? darkStyles.container : lightStyles.container;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={containerStyles}>
      <h1>Next.js Dark and Light Mode Example</h1>
      <ThemeToggle />
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer ut
        neque malesuada, vehicula orci a, viverra risus. Suspendisse vitae odio
        pretium, pellentesque enim et, gravida lorem. Phasellus blandit, velit
        in volutpat ultrices, lorem elit vestibulum dui, et fermentum nulla
        felis vel lorem.
      </p>
      </main>
    </>
  )
}
